export default {
	"array-bracket-newline": "off",
	"array-bracket-spacing": "error",
	"array-element-newline": "off",
	"arrow-parens": "off",
	"arrow-spacing": "error",
	"block-spacing": "off",
	"brace-style": "off",
	"callback-return": "off",
	"comma-dangle": "off",
	"comma-spacing": "off",
	"comma-style": "error",
	"computed-property-spacing": "error",
	"dot-location": ["error", "property"],
	"eol-last": "off",
	"func-call-spacing": "off",
	"function-call-argument-newline": ["error", "consistent"],
	"function-paren-newline": "off",
	"generator-star-spacing": "off",
	"global-require": "off",
	"handle-callback-err": "off",
	"id-blacklist": "error",
	"implicit-arrow-linebreak": "off",
	indent: "off",
	"indent-legacy": "off",
	"jsx-quotes": "error",
	"key-spacing": "off",
	"keyword-spacing": "off",
	"line-comment-position": "error",
	"linebreak-style": "error",
	"lines-around-comment": "off",
	"lines-around-directive": "error",
	"lines-between-class-members": "off",
	"max-len": "off",
	"max-statements-per-line": "error",
	"multiline-comment-style": "error",
	"multiline-ternary": "off",
	"new-parens": "error",
	"newline-after-var": "error",
	"newline-before-return": "error",
	"newline-per-chained-call": [
		"error",
		{
			ignoreChainWithDepth: 4,
		},
	],
	"no-buffer-constructor": "off",
	"no-catch-shadow": "off",
	"no-confusing-arrow": "off",
	"no-extra-parens": "off",
	"no-extra-semi": "off",
	"no-floating-decimal": "error",
	"no-mixed-operators": "off",
	"no-mixed-requires": "off",
	"no-mixed-spaces-and-tabs": "off",
	"no-multi-spaces": [
		"error",
		{
			exceptions: {
				BinaryExpression: true,
				Property: false,
			},
		},
	],
	"no-multiple-empty-lines": [
		"error",
		{
			max: 1,
			maxBOF: 1,
			maxEOF: 1,
		},
	],
	"no-native-reassign": "off",
	"no-negated-in-lhs": "off",
	"no-new-object": "error",
	"no-new-require": "off",
	"no-new-symbol": "error",
	"no-path-concat": "off",
	"no-process-env": "off",
	"no-process-exit": "off",
	"no-restricted-modules": "off",
	"no-return-await": "off",
	"no-spaced-func": "off",
	"no-sync": "off",
	"no-tabs": "off",
	"no-trailing-spaces": "error",
	"no-whitespace-before-property": "error",
	"nonblock-statement-body-position": "error",
	"object-curly-newline": "off",
	"object-curly-spacing": "off",
	"object-property-newline": [
		"error",
		{
			allowAllPropertiesOnSameLine: true,
		},
	],
	"one-var-declaration-per-line": "error",
	"operator-linebreak": "off",
	"padded-blocks": [
		"error",
		{
			blocks: "never",
			classes: "never",
			switches: "never",
		},
		{
			allowSingleLineBlocks: true,
		},
	],
	"padding-line-between-statements": "off",
	"prefer-reflect": "off",
	"quote-props": ["error", "as-needed"],
	quotes: "off",
	"rest-spread-spacing": "error",
	semi: "off",
	"semi-spacing": "error",
	"semi-style": "error",
	"space-before-blocks": "off",
	"space-before-function-paren": "off",
	"space-in-parens": "error",
	"space-infix-ops": "off",
	"space-unary-ops": "error",
	"spaced-comment": [
		"error",
		"always",
		{
			block: {
				balanced: true,
			},
		},
	],
	"switch-colon-spacing": "error",
	"template-curly-spacing": "error",
	"template-tag-spacing": "error",
	"wrap-iife": [
		"error",
		"inside",
		{
			functionPrototypeMethods: true,
		},
	],
	"wrap-regex": "off",
	"yield-star-spacing": ["error", "before"],
};
