export default {
	"accessor-pairs": "error",
	"arrow-body-style": [
		"error",
		"as-needed",
		{
			requireReturnForObjectLiteral: false,
		},
	],
	"block-scoped-var": "error",
	camelcase: [
		"error",
		{
			properties: "never",
		},
	],
	"capitalized-comments": [
		"error",
		"always",
		{
			ignoreConsecutiveComments: true,
		},
	],
	"class-methods-use-this": "off",
	complexity: "off",
	"consistent-return": "off",
	"consistent-this": ["error", "self"],
	curly: "error",
	"default-case": "error",
	"default-case-last": "error",
	"default-param-last": "off",
	"dot-notation": "off",
	eqeqeq: "error",
	"func-name-matching": [
		"error",
		"always",
		{
			includeCommonJSModuleExports: true,
		},
	],
	"func-names": "error",
	"func-style": ["error", "declaration"],
	"grouped-accessor-pairs": ["error", "getBeforeSet"],
	"guard-for-in": "error",
	"id-denylist": "error",
	"id-length": [
		"error",
		{
			min: 1,
			max: 65,
		},
	],
	"id-match": "off",
	"init-declarations": "off",
	"logical-assignment-operators": [
		"error",
		"always",
		{
			enforceForIfStatements: true,
		},
	],
	"max-classes-per-file": "error",
	"max-depth": "off",
	"max-lines": "off",
	"max-lines-per-function": "off",
	"max-nested-callbacks": "error",
	"max-params": "off",
	"max-statements": "off",
	"new-cap": "error",
	"no-alert": "error",
	"no-array-constructor": "off",
	"no-bitwise": "error",
	"no-caller": "error",
	"no-case-declarations": "error",
	"no-console": [
		"error",
		{
			allow: ["error"],
		},
	],
	"no-continue": "error",
	"no-delete-var": "error",
	"no-div-regex": "error",
	"no-else-return": "error",
	"no-empty": "error",
	"no-empty-function": "off",
	"no-empty-static-block": "error",
	"no-eq-null": "error",
	"no-eval": "error",
	"no-extend-native": "error",
	"no-extra-bind": "error",
	"no-extra-boolean-cast": [
		"error",
		{
			enforceForInnerExpressions: true,
		},
	],
	"no-extra-label": "error",
	"no-global-assign": "error",
	"no-implicit-coercion": [
		"error",
		{
			disallowTemplateShorthand: true,
		},
	],
	"no-implicit-globals": [
		"error",
		{
			lexicalBindings: true,
		},
	],
	"no-implied-eval": "off",
	"no-inline-comments": "error",
	"no-invalid-this": "off",
	"no-iterator": "error",
	"no-label-var": "error",
	"no-labels": "error",
	"no-lone-blocks": "error",
	"no-lonely-if": "error",
	"no-loop-func": "off",
	"no-magic-numbers": "off",
	"no-multi-assign": "error",
	"no-multi-str": "error",
	"no-negated-condition": "error",
	"no-nested-ternary": "off",
	"no-new": "error",
	"no-new-func": "error",
	"no-new-wrappers": "error",
	"no-nonoctal-decimal-escape": "error",
	"no-object-constructor": "error",
	"no-octal": "error",
	"no-octal-escape": "error",
	"no-param-reassign": "error",
	"no-plusplus": "off",
	"no-proto": "error",
	"no-redeclare": "off",
	"no-regex-spaces": "error",
	"no-restricted-exports": "off",
	"no-restricted-globals": "off",
	"no-restricted-imports": "off",
	"no-restricted-properties": "off",
	"no-restricted-syntax": ["error", "WithStatement"],
	"no-return-assign": "error",
	"no-script-url": "error",
	"no-sequences": [
		"error",
		{
			allowInParentheses: false,
		},
	],
	"no-shadow": "off",
	"no-shadow-restricted-names": "error",
	"no-ternary": "off",
	"no-throw-literal": "off",
	"no-undef-init": "error",
	"no-undefined": "off",
	"no-underscore-dangle": [
		"error",
		{
			enforceInMethodNames: true,
			enforceInClassFields: true,
			allowInArrayDestructuring: false,
			allowInObjectDestructuring: false,
		},
	],
	"no-unneeded-ternary": "error",
	"no-unused-expressions": "off",
	"no-unused-labels": "error",
	"no-useless-call": "error",
	"no-useless-catch": "error",
	"no-useless-computed-key": "error",
	"no-useless-concat": "error",
	"no-useless-constructor": "off",
	"no-useless-escape": "error",
	"no-useless-rename": "error",
	"no-useless-return": "error",
	"no-var": "error",
	"no-void": "error",
	"no-warning-comments": [
		"error",
		{
			location: "anywhere",
		},
	],
	"no-with": "error",
	"object-shorthand": [
		"error",
		"always",
		{
			avoidExplicitReturnArrows: true,
		},
	],
	"one-var": [
		"error",
		{
			var: "always",
			let: "always",
			const: "consecutive",
			separateRequires: true,
		},
	],
	"operator-assignment": "error",
	"prefer-arrow-callback": [
		"error",
		{
			allowUnboundThis: false,
		},
	],
	"prefer-const": "error",
	"prefer-destructuring": "off",
	"prefer-exponentiation-operator": "error",
	"prefer-named-capture-group": "error",
	"prefer-numeric-literals": "error",
	"prefer-object-has-own": "error",
	"prefer-object-spread": "error",
	"prefer-promise-reject-errors": "off",
	"prefer-regex-literals": [
		"error",
		{
			disallowRedundantWrapping: true,
		},
	],
	"prefer-rest-params": "error",
	"prefer-spread": "error",
	"prefer-template": "error",
	radix: ["error", "as-needed"],
	"require-await": "off",
	"require-unicode-regexp": ["error", { requireFlag: "v" }],
	"require-yield": "error",
	"sort-imports": "error",
	"sort-keys": "off",
	"sort-vars": "off",
	strict: "error",
	"symbol-description": "error",
	"vars-on-top": "error",
	yoda: [
		"error",
		"always",
		{
			onlyEquality: true,
		},
	],
};
